name: check-last-release

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    #
    #
    # Build image
    - name: Build image
      run: docker build -t check-last-release:bootstrap check-last-release/

    #
    #
    # Run script
    - name: Check current commits
      env:
        SLACK_API_HOOK: ${{ secrets.SLACK_API_HOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker run --rm --env GITHUB_TOKEN --env SLACK_API_HOOK check-last-release:bootstrap
