name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      TAG: "TEST"
      REPO: front-end
      KBST_DOCKER_IMAGE: runner:${{ github.sha }}
      TEST_DOCKER_IMAGE: test:${{ github.sha }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '4.x'
    - run: npm install
    - run: npm test
    - name: Build image
      env:
        DOCKER_BUILDKIT: 1
      run: docker build -t $TEST_DOCKER_IMAGE test/
    - name: Test image
      env:
        DOCKER_BUILDKIT: 1
      run: make test