name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: dreddick 
      COMMIT: ${{ github.sha }}
      REPO: front-end
    steps:
    - uses: actions/checkout@v2

    #
    #
    # Run node tests in docker image
    - name: Test
      env:
        DOCKER_BUILDKIT: 1
      run: make test

    #
    #
    # Build docker image for service
    - name: Build docker image
      uses: docker/build-push-action@v1
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        push: false
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

    #
    #
    # Run simple test against built container
    - name: Test docker image
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      env:
        DOCKER_BUILDKIT: 1
      run: ./test/container.sh

    #
    #
    # Push to dockerhub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true